"""Data-access for the meal planner + grocery list (Chunk E).

Plans hold entries (each pointing at a recipe OR a place); the grocery list is generated by
the client-side aggregator (which reuses the scaling engine) and persisted here so its
checked/manual state survives regeneration — only recipe-derived quantities are refreshed.
"""
from __future__ import annotations

import sqlite3
from datetime import datetime, timezone

from .schemas import (
    EntryIn, EntryOut, EntryPatch, GroceryItemOut, GroceryLineIn, ManualItemIn,
    MealPlanCard, MealPlanOut,
)


def _now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def _touch(conn: sqlite3.Connection, plan_id: int) -> None:
    conn.execute("UPDATE meal_plan SET updated_at = ? WHERE id = ?", (_now(), plan_id))


# --------------------------------------------------------------------------- #
# Plans
# --------------------------------------------------------------------------- #
def create_plan(conn: sqlite3.Connection, start_date: str, title: str | None) -> int:
    now = _now()
    cur = conn.execute(
        "INSERT INTO meal_plan(start_date, title, created_at, updated_at) VALUES (?, ?, ?, ?)",
        (start_date, title, now, now),
    )
    return cur.lastrowid


def list_plans(conn: sqlite3.Connection) -> list[MealPlanCard]:
    rows = conn.execute(
        """
        SELECT p.id, p.start_date, p.title,
               (SELECT COUNT(*) FROM meal_plan_entry e WHERE e.plan_id = p.id) AS entry_count
        FROM meal_plan p ORDER BY p.start_date DESC, p.id DESC
        """
    ).fetchall()
    return [MealPlanCard(**dict(r)) for r in rows]


def _entries(conn: sqlite3.Connection, plan_id: int) -> list[EntryOut]:
    rows = conn.execute(
        "SELECT * FROM meal_plan_entry WHERE plan_id = ? ORDER BY day_index, sort_order, id",
        (plan_id,),
    ).fetchall()
    out: list[EntryOut] = []
    for e in rows:
        if e["recipe_id"] is not None:
            r = conn.execute(
                "SELECT title, hero_image FROM recipe WHERE id = ?", (e["recipe_id"],)
            ).fetchone()
            kind, title, hero = "recipe", (r["title"] if r else "(deleted recipe)"), (r["hero_image"] if r else None)
        else:
            r = conn.execute(
                "SELECT name, hero_image FROM place WHERE id = ?", (e["place_id"],)
            ).fetchone()
            kind, title, hero = "place", (r["name"] if r else "(deleted place)"), (r["hero_image"] if r else None)
        out.append(EntryOut(
            id=e["id"], day_index=e["day_index"], meal_slot=e["meal_slot"], scale=e["scale"],
            sort_order=e["sort_order"], kind=kind, recipe_id=e["recipe_id"], place_id=e["place_id"],
            title=title, hero_image=hero,
        ))
    return out


def get_plan(conn: sqlite3.Connection, plan_id: int) -> MealPlanOut | None:
    p = conn.execute("SELECT * FROM meal_plan WHERE id = ?", (plan_id,)).fetchone()
    if p is None:
        return None
    return MealPlanOut(
        id=p["id"], start_date=p["start_date"], title=p["title"],
        created_at=p["created_at"], updated_at=p["updated_at"], entries=_entries(conn, plan_id),
    )


def delete_plan(conn: sqlite3.Connection, plan_id: int) -> bool:
    conn.execute("DELETE FROM meal_plan_entry WHERE plan_id = ?", (plan_id,))
    conn.execute("DELETE FROM grocery_item WHERE plan_id = ?", (plan_id,))
    cur = conn.execute("DELETE FROM meal_plan WHERE id = ?", (plan_id,))
    return cur.rowcount > 0


# --------------------------------------------------------------------------- #
# Entries
# --------------------------------------------------------------------------- #
def add_entry(conn: sqlite3.Connection, plan_id: int, data: EntryIn) -> int:
    cur = conn.execute(
        """
        INSERT INTO meal_plan_entry(plan_id, day_index, meal_slot, recipe_id, place_id, scale, sort_order)
        VALUES (?, ?, ?, ?, ?, ?, ?)
        """,
        (plan_id, data.day_index, data.meal_slot, data.recipe_id, data.place_id, data.scale, data.sort_order),
    )
    _touch(conn, plan_id)
    return cur.lastrowid


def update_entry(conn: sqlite3.Connection, entry_id: int, patch: EntryPatch) -> bool:
    e = conn.execute("SELECT plan_id, day_index, meal_slot, scale, sort_order FROM meal_plan_entry WHERE id = ?", (entry_id,)).fetchone()
    if e is None:
        return False
    conn.execute(
        "UPDATE meal_plan_entry SET day_index = ?, meal_slot = ?, scale = ?, sort_order = ? WHERE id = ?",
        (
            patch.day_index if patch.day_index is not None else e["day_index"],
            patch.meal_slot if patch.meal_slot is not None else e["meal_slot"],
            patch.scale if patch.scale is not None else e["scale"],
            patch.sort_order if patch.sort_order is not None else e["sort_order"],
            entry_id,
        ),
    )
    _touch(conn, e["plan_id"])
    return True


def delete_entry(conn: sqlite3.Connection, entry_id: int) -> bool:
    e = conn.execute("SELECT plan_id FROM meal_plan_entry WHERE id = ?", (entry_id,)).fetchone()
    if e is None:
        return False
    conn.execute("DELETE FROM meal_plan_entry WHERE id = ?", (entry_id,))
    _touch(conn, e["plan_id"])
    return True


# --------------------------------------------------------------------------- #
# Grocery list
# --------------------------------------------------------------------------- #
def _item_out(row: sqlite3.Row) -> GroceryItemOut:
    return GroceryItemOut(
        id=row["id"], name=row["name"], unit=row["unit"], display=row["display"],
        base=row["base"], family=row["family"], aisle=row["aisle"],
        checked=row["checked"], manual=row["manual"],
        recipes=[r for r in (row["recipes"] or "").split("|") if r],
        sort_order=row["sort_order"],
    )


def list_grocery(conn: sqlite3.Connection, plan_id: int) -> list[GroceryItemOut]:
    rows = conn.execute(
        "SELECT * FROM grocery_item WHERE plan_id = ? ORDER BY aisle, name, id", (plan_id,)
    ).fetchall()
    return [_item_out(r) for r in rows]


def generate_grocery(conn: sqlite3.Connection, plan_id: int, items: list[GroceryLineIn]) -> list[GroceryItemOut]:
    """Replace recipe-derived items with the freshly computed ones, preserving the checked
    state of matching (name, unit) lines and keeping all manual items untouched (spec §17)."""
    # Remember prior checked state, matched on name+unit.
    prior = {
        (r["name"].lower(), (r["unit"] or "").lower()): r["checked"]
        for r in conn.execute("SELECT name, unit, checked FROM grocery_item WHERE plan_id = ?", (plan_id,))
    }
    # Drop only the recipe-derived rows; manual items stay.
    conn.execute("DELETE FROM grocery_item WHERE plan_id = ? AND manual = 0", (plan_id,))
    for i, it in enumerate(items):
        checked = prior.get((it.name.lower(), (it.unit or "").lower()), 0)
        conn.execute(
            """
            INSERT INTO grocery_item(plan_id, name, unit, display, base, family, aisle, checked, manual, recipes, sort_order)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, 0, ?, ?)
            """,
            (plan_id, it.name, it.unit, it.display, it.base, it.family, it.aisle, checked, "|".join(it.recipes), i),
        )
    _touch(conn, plan_id)
    return list_grocery(conn, plan_id)


def add_manual_item(conn: sqlite3.Connection, plan_id: int, data: ManualItemIn) -> GroceryItemOut:
    cur = conn.execute(
        """
        INSERT INTO grocery_item(plan_id, name, unit, display, base, family, aisle, checked, manual, recipes, sort_order)
        VALUES (?, ?, ?, ?, NULL, 'none', ?, 0, 1, '', 0)
        """,
        (plan_id, data.name.strip(), data.unit, data.display, data.aisle),
    )
    row = conn.execute("SELECT * FROM grocery_item WHERE id = ?", (cur.lastrowid,)).fetchone()
    return _item_out(row)


def set_checked(conn: sqlite3.Connection, item_id: int, checked: bool) -> bool:
    cur = conn.execute("UPDATE grocery_item SET checked = ? WHERE id = ?", (1 if checked else 0, item_id))
    return cur.rowcount > 0


def delete_item(conn: sqlite3.Connection, item_id: int) -> bool:
    cur = conn.execute("DELETE FROM grocery_item WHERE id = ?", (item_id,))
    return cur.rowcount > 0
